# Source formatting tool
INDENT:=clang-format40 -i

SRC:=config.cpp test-main.cpp

RM:=rm -f

all: tests Makefile.FreeBSD

clean: test-config-clean
	$(RM) *.o
	$(RM) core

tests: test-config
	./test-config

test-main.o: test-main.cpp
	${CXX} ${CXXFLAGS} -g -c test-main.cpp -o $@

test-config: config.cpp ../config.h ../config.cpp catch.hpp test-main.o
	${CXX} ${CXXFLAGS} -g test-main.o config.cpp ../config.cpp -o $@

test-config-clean:
	$(RM) test-config

catch.hpp:
	wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp

format:
	$(INDENT) $(SRC)
