RM:=rm -f

all:
	$(MAKE) -C src -f Makefile.FreeBSD all

test:
	$(MAKE) -C src/test -f Makefile.FreeBSD all

format:
	$(MAKE) -C src -f Makefile.FreeBSD format
	$(MAKE) -C src/test -f Makefile.FreeBSD format

clean:
	$(MAKE) -C src -f Makefile.FreeBSD clean
	$(MAKE) -C src/test -f Makefile.FreeBSD clean

distclean:
	$(MAKE) -C src -f Makefile.FreeBSD clean
	$(MAKE) -C src/test -f Makefile.FreeBSD clean
	$(RM) clock
