RM:=rm -f

all:
	cd src; $(MAKE) all

test:
	cd src/test; $(MAKE) all

format:
	cd src; $(MAKE) format
	cd src/test; $(MAKE) format

clean:
	cd src; $(MAKE) clean
	cd src/test; $(MAKE) clean

distclean:
	cd src; $(MAKE) clean
	cd src/test; $(MAKE) clean
	$(RM) clock
