FLTKCONFIG:=/usr/local/bin/fltk-config
CXXFLAGS_FLTK!=${FLTKCONFIG} --cxxflags
LDFLAGS_FLTK!=${FLTKCONFIG} --use-images --ldflags

CXXFLAGS_CURL!=curl-config --cflags
LDFLAGS_CURL!=curl-config --libs

CXXFLAGS_JSON-C!=pkg-config json-c --cflags
LDFLAGS_JSON-C!=pkg-config json-c --libs

CXXFLAGS_DBG=
.ifdef DEBUG
CXXFLAGS_DBG=-g
.endif

CXXFLAGS=${CXXFLAGS_FLTK} ${CXXFLAGS_CURL} ${CXXFLAGS_JSON-C} -Wall -I. -I.. ${CXXFLAGS_DBG} -std=c++11
LDFLAGS=${LDFLAGS_FLTK} ${LDFLAGS_CURL} ${LDFLAGS_JSON-C}

RM:=rm -f

# Source formatting tool
INDENT:=clang-format40 -i

# Final executable name.
PROGRAM=../clock

INC=app.h config.h json.hpp msgline.h timeline.h
SRC=app.cpp config.cpp main.cpp msgline.cpp timeline.cpp
OBJ=app.o config.o main.o msgline.o timeline.o

all: ${PROGRAM} BSDmakefile
	@echo "Compiling client for FreeBSD done."

json.hpp:
	wget https://raw.githubusercontent.com/nlohmann/json/master/src/json.hpp

${PROGRAM}: ${OBJ} ${SRC} ${INC}
	${CXX} ${OBJ} ${LDFLAGS} -o ${PROGRAM}

.SUFFIXES: .o .cpp
.cpp.o: ${INC}
	${CXX} ${CXXFLAGS} -c ${.IMPSRC} -o  ${.TARGET}

format: ${INC}
	${INDENT} ${SRC} ${INC}

clean:
	${RM} ${PROGRAM} ${OBJ}
	${RM} core

distclean: clean
	$(RM) json.hpp
